[#98] Refactor class components to hooks
kammanz/raptors-app pull request #124
Opened 2020-06-25 21:26 UTC by kammanz

Refactored the two class components, header and list, into function components.

What's completed:

- In header component, useEffect makes the getTeams call
- In list component, useEffect and useRef are used to scroll back to top on team select

2020-06-25 21:28 UTC, kammanz commented
Ready for review.

2020-06-26 01:27 UTC, Tumne requested changes

2020-06-26 01:27 UTC, Tumne commented on src/components/header/index.js
> +  }, []);
As per our slack convo, your code is correct, the reason you see the warning is a side effect of `useEffect`. Essentially it's a scoping issue with the `getTeams`, `pathname`, and `history` params. The easiest thing would be to es lint disable the issue, but I don't think it'll be necessary.

Instead, if you move that function parameter into it's own const, it eliminates it cleanly:

```
  const getTeamsCallback = () => {
    getTeams(pathname, history);
  };

  useEffect(getTeamsCallback, []);
```

I know, it's dumb, but that's the way she goes. It's either solution 1 or solution 4 in this stackoverflow comment:

https://stackoverflow.com/a/60327893

2020-06-26 01:27 UTC, Tumne commented on src/components/players/list/index.js
> +  });
The concept behind `useEffect` is that there is no need to do a compare within the callback function: `if (selectedTeamRef.current !== selectedTeam)`

The proper usage would be to send in `selectedTeam` as a dependency. Then it acts like a `componentDidUpdate` and will compare `if (selectedTeamPrev !== selectedTeam)`

In that case we can simplify our useEffect to this:

```
  const domRef = useRef();

  useEffect(() => {
    domRef.current.scrollTo(0, 0);
  }, [selectedTeam]);
```

notice, that `selectedTeam` is the dependency injected and useEffect is listening to changes once `selectedTeam` changes.

2020-06-26 02:00 UTC, Tumne commented on src/components/players/list/index.js
> +  });
Further refined, just use `teamId`:
```
  useEffect(() => {
    domRef.current.scrollTo(0, 0);
  }, [teamId]);
```

2020-06-26 15:13 UTC, kammanz commented
Ready for review.

2020-06-26 17:24 UTC, kammanz commented
Ready for review.

2020-06-26 19:08 UTC, merged