[#113] Elements no longer highlightable
kammanz/raptors-app pull request #131
Opened 2020-06-27 22:13 UTC by kammanz

2020-06-27 22:13 UTC, kammanz commented
Ready for review.

2020-06-28 00:19 UTC, kammanz commented
Ready for review.

2020-06-28 12:57 UTC, Tumne requested changes
Looks good, Minor fixes and some design changes, (adding another gif image).

2020-06-28 12:57 UTC, Tumne commented on src/components/games/index.module.scss
> +  height: calc(100vh - 90px);
`height: calc(100vh - 45px);`

2020-06-28 12:57 UTC, Tumne commented on src/components/standings/index.module.scss
> +  height: calc(100vh - 90px);
`height: calc(100vh - 45px);`

2020-06-28 12:57 UTC, Tumne commented on src/components/standings/index.js
> +import lebron from 'assets/gifs/lebron.gif';
rename
```
import standingsGif from 'assets/gifs/standings.gif';
```

2020-06-28 12:57 UTC, Tumne commented on src/components/games/index.js
> +import lebron from 'assets/gifs/lebron.gif';
rename
```
import gamesGif from 'assets/gifs/games.gif';
```

where this should be the gif: https://media3.giphy.com/media/5n1XqQh0DskgKMKejY/giphy.gif

2020-07-02 23:43 UTC, kammanz commented
Ready for review.

2020-07-02 23:48 UTC, Tumne reviewed
A reminder

2020-07-02 23:48 UTC, Tumne commented on src/components/header/navMenu.js
> +  };
I believe this was meant for PR #130, whoops again.
Try to keep your PRs clean when switching between them.

2020-07-03 00:02 UTC, Tumne commented on src/components/header/navMenu.js
> +  };
nvm, I see what you did, consider resolved

2020-07-03 00:02 UTC, Tumne approved these changes
Approved and completed minor UI changes

2020-07-03 00:02 UTC, merged