Rap 19  replace nba endpoint
kammanz/raptors-app pull request #20
Opened 2020-01-25 00:51 UTC by kammanz

Completed issue 19. There's a problem though, it seems there is only one size for images and we wanted a large image to appear on the right side when user selects player. It seems there are multiples sizes for video, but not image, according to the bottom of the npm page ...
https://www.npmjs.com/package/nba-api-client  

If I missed something please let me know.

2020-01-28 20:58 UTC, Tumne requested changes
Works well. There are some clean up that's needed. 

Also I noticed that this app is not properly organized and would be good to restructure the codebase before it starts to grow. I will create a separate ticket for this.

2020-01-28 20:58 UTC, Tumne commented on package.json
> +  "proxy": "http://data.nba.net",
If not using, remove

2020-01-28 20:58 UTC, Tumne commented on src/actions/actions.js
> +    dispatch({ type: 'SELECT_PLAYER', payload: {...response.data.league.standard.stats.latest, playerName, playerId }});
Missing space before curly bracket `{ ...response.data`

2020-01-28 20:58 UTC, Tumne commented on src/components/PlayerDetails.js
> +        const { selectPlayer } = props;
Tabbed over too much

2020-01-28 20:58 UTC, Tumne commented on src/components/PlayerDetails.js
> +            <div>Steals: {selectPlayer.steals}</div>
Can we use a destruct for all these values

`const { playerName, playerId, points, ppg, blocks, steals } = selectPlayer;`

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +        // this.props.playerHeadshot();
Remove commented out code.

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +        console.log('this.props.getPlayers()', this.props.getPlayers());
Always remove console.log in PR. Unless, you need to leave a console, in those very few cases, use `console.info('this.props.getPlayers()', this.props.getPlayers());`

I'll let you decide between one of these choices

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +        console.log('players', players);
Same comment as above, remove

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +    }
Remove this unused function

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +    // }
Remove commented out code

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +        console.log(this.props.players, 'this.props render in playerslist' );
Remove this

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +    console.log(state.players);
Remove

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +    // return { playerHeadshot: state.playerHeadshot }
Remove

2020-01-28 20:58 UTC, Tumne commented on src/components/Players.js
> +                <br/>
Remove this `<br/>` try to avoid these in general. We should be using css instead.

2020-02-06 00:10 UTC, kammanz commented on src/components/Players.js
> +        // this.props.playerHeadshot();
I deleted Players.js altogether, extraneous file, PlayersList.js is the one being used.

2020-02-07 15:53 UTC, Tumne commented on src/actions/actions.js
> +    dispatch({ type: 'SELECT_PLAYER', payload: {...response.data.league.standard.stats.latest, playerName, playerId }});
Not competed yet

2020-02-07 16:34 UTC, Tumne approved these changes

2020-02-07 16:34 UTC, merged