[#36] Player details stats section
kammanz/raptors-app pull request #48
Opened 2020-03-17 22:51 UTC by kammanz

Completed player details stats section.

2020-03-17 22:58 UTC, kammanz commented
Ready for review

2020-03-18 07:19 UTC, Tumne requested changes
There will need to be some more necessary fixes.

2020-03-18 07:19 UTC, Tumne commented on src/components/players/playerDetails/mainStats.js
> +}
As you briefly mentioned before. It seems that the component for `MaintStats` and `AllStats` are exactly the same js. The only different is slight differences between the scss. 

Firstly, make one single component called `Stat` (notice the singular name)

Next, implement the css for this table:

<img width="444" alt="Screen Shot 2020-03-18 at 3 09 37 AM" src="https://user-images.githubusercontent.com/623755/76934674-f36bdd80-68c5-11ea-845c-fbc4afe42ce2.png">

Then in your `Stat` component, have a boolean prop called `isQuickStats`. If true, then adjust the css accordingly. I'll let you figure that one out. Let me know if you need clarification on this.

2020-03-18 07:19 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                <div className={styles.mainStatsContainer}>
There is unnecessary padding, entire section not lining up flush with stats red title.

<img width="440" alt="Screen Shot 2020-03-18 at 3 16 16 AM" src="https://user-images.githubusercontent.com/623755/76935076-d257bc80-68c6-11ea-9879-9d218d355c16.png">

2020-03-20 15:37 UTC, kammanz commented
Changes made, ready for review. I also fixed a couple of bugs, the height of the details card is now 100%, and there was a strange margin top bug with the players list, fixed it.

2020-03-20 21:18 UTC, Tumne requested changes
There are a bunch of incorrect values for the stats, also want to refactor

2020-03-20 21:18 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={true} title="Reb" stat={player.totReb} />
This is my bad. This value/title should be the `rpg` (rebounds per game):

<img width="130" alt="Screen Shot 2020-03-20 at 5 03 03 PM" src="https://user-images.githubusercontent.com/623755/77206197-c63d4c00-6acc-11ea-851a-960ba56f65aa.png">

If you could change that.

2020-03-20 21:18 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={false} title="Reb" stat={player.totReb} />
Same here. `Rpg` not `Reb`.

2020-03-20 21:18 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={false} title="Fg%" stat={player.gamesPlayed} />
This value should be `player.fgp`

2020-03-20 21:18 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={false} title="3P%" stat={player.gamesPlayed} />
This value should be `player.tpp`

2020-03-20 21:18 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={false} title="Ft%" stat={player.fgp} />
This value should be `player.ftp`

2020-03-20 22:17 UTC, Tumne commented
As discussed, let's make the title a common component as well `<Title />`:

<img width="392" alt="Screen Shot 2020-03-20 at 6 16 47 PM" src="https://user-images.githubusercontent.com/623755/77210288-fee22300-6ad6-11ea-9794-03474f051d60.png">

2020-03-20 23:55 UTC, kammanz commented
Made changes, ready for review.

2020-03-22 23:30 UTC, Tumne requested changes
Some further changes needed and clean up.

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +
remove space

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +    console.log(player);
remove `console.log` and space

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.module.scss
> +.mainStatsContainer {
rename to `.statsContainer {`

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={true} title="FG%" stat={player.fgp} />
If the prop being sent is a `true` boolean, simplify be just sending the prop name `isQuickStats` and it will be interpreted as `true` by the component:

```
     <Stats isQuickStats title="Ppg" stat={player.ppg} />
     <Stats isQuickStats title="Rpg" stat={player.rpg} />
     <Stats isQuickStats title="Ast" stat={player.assists} />
     <Stats isQuickStats title="FG%" stat={player.fgp} />
```

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={false} title="Pts" stat={player.points} />
If the prop being sent is a `false` boolean, simplify by NOT sending the prop name `isQuickStats` and it will be interpreted as `false` by the component:

```
    <Stats title="GP" stat={player.gamesPlayed} />
    <Stats title="Min" stat={player.min} />
    <Stats title="Fg%" stat={player.fgp} />
    <Stats title="3P%" stat={player.tpp} />
    <Stats title="Ft%" stat={player.ftp} />
    <Stats title="Rpg" stat={player.rpg} />
    <Stats title="Ast" stat={player.assists} />
    <Stats title="Blk" stat={player.blocks} />
    <Stats title="Stl" stat={player.steals} />
    <Stats title="Pf" stat={player.pFouls} />
    <Stats title="To" stat={player.turnovers} />
    <Stats title="Pts" stat={player.points} />
```

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +                <Title title="Stats" />
Also, for all these title string variables, let's not capitalize the first letter unless that's how it will be displayed. Seeing that everything will be uppercase in css it will be fine, but the convention is lowercase or uppercase the letters, but not capitalize.

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.module.scss
> +}
Remove this `.title` css, not being used.

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/playerDetails.js
> +
remove extra space

2020-03-22 23:30 UTC, Tumne commented on src/components/players/playerDetails/stats.js
> +
Clean this one up a bit:

```
const Stats = ({ title, stat, isQuickStats }) => {
    return (
        <div className={isQuickStats ? styles.quickStatContainer : styles.container}>
            {isQuickStats ?
              <Title title={title} /> :
              <div className={styles.title}>{title}</div>
            }
            <div className={styles.stat}>{stat}</div>
        </div>
    )
}
```

2020-03-24 00:56 UTC, kammanz commented on src/components/players/playerDetails/playerDetails.js
> +                    <Stats isQuickStats={true} title="FG%" stat={player.fgp} />
True, thanks for suggestion.

2020-03-24 01:08 UTC, kammanz commented
Changes made, ready for pr review.

2020-03-24 13:47 UTC, Tumne commented
Looks good, even tho it's good to go, I decided that it needed further refactoring. 
I have taken the liberty of cleaning up the code in a separate PR #51. Before merging everything let's discuss the clean up over the sprint meeting.

2020-03-25 03:51 UTC, Tumne commented
Merged PR #51 into this Branch. Good to go

🚀

2020-03-25 03:52 UTC, merged